# Generated by Django 6.0.1 on 2026-01-20 18:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='qrcodepass',
            name='max_uses',
        ),
    ]
